language: c
compiler: gcc
sudo: required
dist: bionic

before_install:
  - export ALL_DEB=$(wget --quiet -O - ${KERNEL_URL}v${KVER}/ | grep -o 'href=".*"' | grep -m1 all | cut -d '"' -f 2)
  - export KVER_BUILD=$(echo $ALL_DEB | cut -d '_' -f 1 | cut -c15-)
  - wget ${KERNEL_URL}v${KVER}/$(wget --quiet -O - ${KERNEL_URL}v${KVER}/ | grep -o 'href=".*"' | grep headers | grep generic | grep -m1 amd64 | cut -d '"' -f 2)
  - wget ${KERNEL_URL}v${KVER}/$ALL_DEB
  - sudo dpkg -i *.deb

script:
  - make CC=$COMPILER KVER=$KVER_BUILD-generic
env:
  global:
    - KERNEL_URL=http://kernel.ubuntu.com/~kernel-ppa/mainline/

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
      env: COMPILER=gcc-9 KVER=5.6-rc5
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-8
      env: COMPILER=gcc-8 KVER=5.6-rc5
    - compiler: gcc
      env: COMPILER=gcc-7 KVER=5.6-rc5
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
      env: COMPILER=gcc-6 KVER=5.6-rc5
    - compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
      env: COMPILER=gcc-9 KVER=4.19.93
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-8
      env: COMPILER=gcc-8 KVER=4.19.93
    - compiler: gcc
      env: COMPILER=gcc-7 KVER=4.19.93
    - compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
      env: COMPILER=gcc-6 KVER=4.19.93
    - compiler: gcc
      env: COMPILER=gcc-7 KVER=4.15.18
